### ISSUE TITLE
关于一个界面多模型显示的问题

### ISSUE THREAD

**Issue by c105ure** [zimanxi/live2d--moc3-withSound--mobile#1]
你好，我是基于安卓的l2d框架开发的，在安卓可以添加多个模型。

**Comment by tohsakrat** [comment]
从他输出的数据对象看，我觉得也应该是预留了多模型同台演出的接口的。
但现在最大的难题是官方文档/注释实在太简略，且没有英/中文……

**Comment by c105ure** [comment]
是的，官方只提供c++的API文档，但是安卓端的库基本上是功能java实现的，初期代码的学习是一件让人非常头疼的事。

**Comment by c105ure** [comment]
是的，看起来确实头疼，我们安卓端的架构我分析是这样的，希望对你有帮助。
![l2d_struct](https://user-images.githubusercontent.com/108248589/176068933-77267cf4-37c8-4758-ae7c-21aa89089564.png)
。
